In [4]:
import pyodbc

try:
    conn = pyodbc.connect(
        r"DRIVER={ODBC Driver 17 for SQL Server};"
        r"SERVER=LAPTOP-VU8OO5GA\SQLEXPRESS;"
        r"DATABASE=Hospital_Supply_Chain;"
        r"Trusted_Connection=yes;"
    )

    print("✅ Connected Successfully!")

    cursor = conn.cursor()
    cursor.execute("SELECT @@VERSION")
    print(cursor.fetchone()[0])

    conn.close()

except Exception as e:
    print(e)

from sqlalchemy import create_engine

✅ Connected Successfully!
Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)
	Oct  8 2022 05:58:25
	Copyright (C) 2022 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Home Single Language 10.0 <X64> (Build 26200: )

In [5]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://@LAPTOP-VU8OO5GA\\SQLEXPRESS/Hospital_Supply_Chain"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Hospitals.csv")

print(df.head())

df.to_sql(
    "Hospitals",
    engine,
    if_exists="append",
    index=False
)

print("Imported Successfully!")

  Hospital_ID      Hospital_Name       City        State Country  \
0        H001  MedCare Bangalore  Bengaluru    Karnataka   India
1        H002    MedCare Chennai    Chennai   Tamil Nadu   India
2        H003  MedCare Hyderabad  Hyderabad    Telangana   India
3        H004     MedCare Mumbai     Mumbai  Maharashtra   India
4        H005       MedCare Pune       Pune  Maharashtra   India

   Bed_Capacity    Hospital_Type Operational_Since Hospital_Tier  \
0           750  Multi-Specialty        2023-01-01        Tier 1
1           650  Multi-Specialty        2023-01-01        Tier 1
2           700  Multi-Specialty        2023-01-01        Tier 1
3           800  Multi-Specialty        2023-01-01        Tier 1
4           500  Multi-Specialty        2023-01-01        Tier 2

  Emergency_Level Trauma_Center  Annual_Patient_Capacity  \
0         Level I           Yes                   275000
1         Level I           Yes                   240000
2         Level I           Yes                   255000
3         Level I           Yes                   300000
4        Level II            No                   180000

   Annual_Procurement_Budget Warehouse_ID
0                 1850000000        WH001
1                 1650000000        WH002
2                 1750000000        WH003
3                 2100000000        WH004
4                 1200000000        WH005
Imported Successfully!

In [7]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Departments.csv")

df.to_sql(
    "Departments",
    engine,
    if_exists="append",
    index=False
)

print("Departments imported successfully!")

Departments imported successfully!

In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Vendors.csv")

df.to_sql(
    "Vendors",
    engine,
    if_exists="append",
    index=False
)

print("✅ Vendors imported successfully!")

✅ Vendors imported successfully!

In [9]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Product_Master.csv")

df.to_sql(
    "Product_Master",
    engine,
    if_exists="append",
    index=False
)

print("✅ Product_Master imported successfully!")

✅ Product_Master imported successfully!

In [10]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Vendor_Product.csv")

df.to_sql(
    "Vendor_Product",
    engine,
    if_exists="append",
    index=False
)

print("✅ Vendor_Product imported successfully!")

✅ Vendor_Product imported successfully!

In [11]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Purchase_Orders.csv")

df.to_sql(
    "Purchase_Orders",
    engine,
    if_exists="append",
    index=False
)

print("✅ Purchase_Orders imported successfully!")

✅ Purchase_Orders imported successfully!

In [12]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Purchase_Order_Lines.csv")
print(df.columns.tolist())
print(df.dtypes)

['PO_Line_ID', 'PO_ID', 'Product_ID', 'Quantity', 'Unit_Cost', 'Line_Total']
PO_Line_ID        str
PO_ID             str
Product_ID        str
Quantity        int64
Unit_Cost     float64
Line_Total    float64
dtype: object

In [13]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Purchase_Order_Lines.csv"
)

df.to_sql(
    "Purchase_Order_Lines",
    engine,
    if_exists="append",
    index=False
)

print("✅ Purchase_Order_Lines imported successfully!")

✅ Purchase_Order_Lines imported successfully!

In [14]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Shipments.csv"
)

print(df.columns.tolist())
print(df.dtypes)

['Shipment_ID', 'PO_ID', 'Vendor_ID', 'Hospital_ID', 'Planned_Delivery_Date', 'Actual_Delivery_Date', 'Ordered_Quantity', 'Received_Quantity', 'Damaged_Quantity', 'Delivery_Variance_Days', 'Delivery_Status', 'Transport_Mode', 'Receiving_Status']
Shipment_ID                 str
PO_ID                       str
Vendor_ID                   str
Hospital_ID                 str
Planned_Delivery_Date       str
Actual_Delivery_Date        str
Ordered_Quantity          int64
Received_Quantity         int64
Damaged_Quantity          int64
Delivery_Variance_Days    int64
Delivery_Status             str
Transport_Mode              str
Receiving_Status            str
dtype: object

In [15]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Shipments.csv"
)

# Convert dates
df["Planned_Delivery_Date"] = pd.to_datetime(df["Planned_Delivery_Date"])
df["Actual_Delivery_Date"] = pd.to_datetime(df["Actual_Delivery_Date"])

df.to_sql(
    "Shipments",
    engine,
    if_exists="append",
    index=False
)

print("✅ Shipments imported successfully!")

✅ Shipments imported successfully!

In [16]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Inventory.csv"
)

print(df.columns.tolist())
print(df.dtypes)

['Inventory_ID', 'Hospital_ID', 'Warehouse_ID', 'Product_ID', 'Current_Stock', 'Reorder_Level', 'Safety_Stock', 'Maximum_Stock', 'Inventory_Value', 'Stock_Status']
Inventory_ID           str
Hospital_ID            str
Warehouse_ID           str
Product_ID             str
Current_Stock        int64
Reorder_Level        int64
Safety_Stock         int64
Maximum_Stock        int64
Inventory_Value    float64
Stock_Status           str
dtype: object

In [17]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Inventory.csv"
)

df.to_sql(
    "Inventory",
    engine,
    if_exists="append",
    index=False
)

print("✅ Inventory imported successfully!")

✅ Inventory imported successfully!

In [18]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Financials_Enterprise.csv"
)

print(df.columns.tolist())
print(df.dtypes)

['Financial_ID', 'PO_ID', 'Vendor_ID', 'Hospital_ID', 'Department_ID', 'Cost_Center', 'Invoice_Number', 'Invoice_Date', 'Payment_Due_Date', 'Payment_Date', 'Transaction_Date', 'Expense_Category', 'Expense_Type', 'Budget_Amount', 'Actual_Amount', 'Variance', 'Variance_Percentage', 'Payment_Method', 'Payment_Status', 'Fiscal_Year', 'Fiscal_Quarter', 'Budget_Status']
Financial_ID               str
PO_ID                      str
Vendor_ID                  str
Hospital_ID                str
Department_ID              str
Cost_Center                str
Invoice_Number             str
Invoice_Date               str
Payment_Due_Date           str
Payment_Date               str
Transaction_Date           str
Expense_Category           str
Expense_Type               str
Budget_Amount          float64
Actual_Amount          float64
Variance               float64
Variance_Percentage    float64
Payment_Method             str
Payment_Status             str
Fiscal_Year                str
Fiscal_Quarter             str
Budget_Status              str
dtype: object

In [20]:
df[df["Payment_Date"].isna()][["Financial_ID", "Payment_Status"]].head(10)

   Financial_ID Payment_Status
0     FIN000001        Pending
7     FIN000008        Pending
9     FIN000010        Pending
13    FIN000014        Pending
23    FIN000024        Pending
29    FIN000030        Pending
65    FIN000066        Pending
67    FIN000068        Pending
71    FIN000072        Pending
72    FIN000073        Pending

In [21]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Financials_Enterprise.csv"
)

# Convert date columns
date_cols = [
    "Invoice_Date",
    "Payment_Due_Date",
    "Payment_Date",
    "Transaction_Date"
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col])

df.to_sql(
    "Financials",
    engine,
    if_exists="append",
    index=False
)

print("✅ Financials imported successfully!")

✅ Financials imported successfully!

In [22]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Patients.csv"
)

print(df.columns.tolist())
print(df.dtypes)

['Patient_ID', 'Hospital_ID', 'Department_ID', 'Age', 'Gender', 'Admission_Date', 'Discharge_Date', 'Length_of_Stay', 'Diagnosis', 'Payment_Type', 'Outcome']
Patient_ID          str
Hospital_ID         str
Department_ID       str
Age               int64
Gender              str
Admission_Date      str
Discharge_Date      str
Length_of_Stay    int64
Diagnosis           str
Payment_Type        str
Outcome             str
dtype: object

In [ ]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Patients.csv"
)

print(df.columns.tolist())
print(df.dtypes)

['Patient_ID', 'Hospital_ID', 'Department_ID', 'Age', 'Gender', 'Admission_Date', 'Discharge_Date', 'Length_of_Stay', 'Diagnosis', 'Payment_Type', 'Outcome']
Patient_ID          str
Hospital_ID         str
Department_ID       str
Age               int64
Gender              str
Admission_Date      str
Discharge_Date      str
Length_of_Stay    int64
Diagnosis           str
Payment_Type        str
Outcome             str
dtype: object

In [23]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Patients.csv"
)

# Convert date columns
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"])
df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"])

df.to_sql(
    "Patients",
    engine,
    if_exists="append",
    index=False
)

print("✅ Patients imported successfully!")

✅ Patients imported successfully!

In [24]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Staff.csv"
)

print(df.columns.tolist())
print(df.dtypes)

['Staff_ID', 'Hospital_ID', 'Department_ID', 'Job_Role', 'Staff_Type', 'Years_Experience', 'Shift', 'Employment_Type', 'Performance_Rating', 'Status']
Staff_ID                  str
Hospital_ID               str
Department_ID             str
Job_Role                  str
Staff_Type                str
Years_Experience        int64
Shift                     str
Employment_Type           str
Performance_Rating    float64
Status                    str
dtype: object

In [25]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Staff.csv"
)

df.to_sql(
    "Staff",
    engine,
    if_exists="append",
    index=False
)

print("✅ Staff imported successfully!")

✅ Staff imported successfully!

In [26]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Date_Dimension.csv"
)

print(df.columns.tolist())
print(df.dtypes)

['Date_Key', 'Date', 'Day', 'Day_Name', 'Week_Number', 'Month', 'Month_Name', 'Quarter', 'Year', 'Fiscal_Year', 'Fiscal_Quarter', 'Is_Weekend', 'Is_Month_Start', 'Day_Of_Year']
Date_Key          int64
Date                str
Day               int64
Day_Name            str
Week_Number       int64
Month             int64
Month_Name          str
Quarter           int64
Year              int64
Fiscal_Year         str
Fiscal_Quarter      str
Is_Weekend          str
Is_Month_Start      str
Day_Of_Year       int64
dtype: object

In [28]:
df[["Is_Weekend","Is_Month_Start"]].head()

  Is_Weekend Is_Month_Start
0        Yes            Yes
1         No             No
2         No             No
3         No             No
4         No             No

In [29]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Bharath Venkatesh\Downloads\Hospital Data\Date_Dimension.csv"
)

df["Date"] = pd.to_datetime(df["Date"])

df.to_sql(
    "Date_Dimension",
    engine,
    if_exists="append",
    index=False
)

print("✅ Date_Dimension imported successfully!")

✅ Date_Dimension imported successfully!